Apply fails in the new StorageClass semantic check
Openstack is failing to apply during semantic check.

Root cause:
A remaining debug line was causing the apply to fail with a
TypeError: not all arguments converted during string formatting

Solution:
Remove the debug code.

Optimization:
The function get_pvc_storageclass was trying to assign a value
before the validation that check if the namespace or pvc's existed.

Reordering the position of the variables allow a better optimization, where the variable will call the functions required when needed.

TEST PLAN:

PASS - apply openstack in a environment that there isn't the
       required namespace/pvc/storageclass.
PASS - apply openstack with rook-ceph only
PASS - apply openstack with netapp only
PASS - block apply when the storage class changed.

Closes-Bug: 2138821

Change-Id: I5503be7b5bce7b7ddf18dfb3066b38f270774445
Signed-off-by: kgoncalv <kayo.goncalvesdacosta@windriver.com>
(cherry picked from commit 858d4c21d90958e9744b660cfc32b43ac2e66f16)